// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:23f59e73-378f-40a2-975e-c8a883f01154",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_mjQ1ziSxH",
    "aws_user_pools_web_client_id": "10bd64mrth6iue7e84jp191oet",
    "oauth": {},
    "aws_mobile_analytics_app_id": "d92d6bd932cf4b66a8d6ad0ef1af70e5",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://ytisqgyfufajjbrxaoen4tzfme.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
