// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:1a2e87fe-5bd0-421f-84f0-cab77f80f653",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_t79RFgJc5",
    "aws_user_pools_web_client_id": "1i5vcnhmcmnuckok83qh5miaam",
    "oauth": {},
    "aws_mobile_analytics_app_id": "aef8d2e8016046fbb19d1a0667ee5848",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://jjcqapvhrrblngmhxkvoyj4kwm.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
